# Generated by Django 4.0.4 on 2022-08-11 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moviesList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.TextField(max_length=4096, verbose_name='内容')),
                ('reply_create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reply_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('reply_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesList.blogpost', verbose_name='所在帖子')),
            ],
        ),
    ]
