# Generated by Django 4.0.4 on 2022-08-13 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesForum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply_topic',
            new_name='reply_Blog',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reply_content',
            new_name='reply_body',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reply_create_date',
            new_name='reply_create_time',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reply_author',
            new_name='reply_user',
        ),
    ]
