# Generated by Django 4.0.4 on 2022-07-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiangyebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(upload_to='imgurl/%Y/%m/%d'),
        ),
    ]
