# Generated by Django 4.0.4 on 2022-07-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moviesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies_name', models.CharField(max_length=32, null=True, verbose_name='moviename')),
                ('classification', models.CharField(blank=True, max_length=32, null=True)),
                ('release_data', models.DateTimeField(blank=True, null=True)),
                ('movies_rating', models.IntegerField(default=2)),
                ('movies_posts', models.DateTimeField(verbose_name='时间')),
                ('img_url', models.ImageField(upload_to='imgurl/', verbose_name='img')),
            ],
        ),
    ]
