# Generated by Django 4.0.4 on 2022-08-06 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='moviesInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies_name', models.CharField(max_length=32, null=True, verbose_name='moviename')),
                ('classification', models.CharField(blank=True, max_length=32, null=True)),
                ('release_data', models.DateTimeField(blank=True, null=True)),
                ('movies_rating', models.IntegerField(default=2)),
                ('movies_posts', models.DateTimeField(verbose_name='时间')),
                ('img_url', models.ImageField(upload_to='imgurl/', verbose_name='img')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesList.category')),
            ],
        ),
    ]
