# Generated by Django 4.0.4 on 2022-08-11 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='movieTitle')),
                ('body', tinymce.models.HTMLField()),
                ('save_number', models.IntegerField(default=0, verbose_name='save_number')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='publish_date')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='userBlog')),
            ],
            options={
                'verbose_name': 'article_table',
                'verbose_name_plural': 'article_table',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviesList.category')),
            ],
        ),
        migrations.CreateModel(
            name='moviesInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies_title', models.CharField(max_length=32, null=True, verbose_name='moviename')),
                ('classification', models.CharField(blank=True, max_length=32, null=True)),
                ('release_data', models.DateTimeField(blank=True, null=True)),
                ('movies_avg_rating', models.IntegerField(default=2)),
                ('movies_posts', models.DateTimeField(verbose_name='时间')),
                ('img_url', models.ImageField(upload_to='imgurl/', verbose_name='img')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost2',
            fields=[
                ('BlogpostObject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='moviesList.blogpost')),
                ('movie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='moviesList.moviesinformation', verbose_name='movies')),
            ],
        ),
    ]
