# Generated by Django 4.0.4 on 2022-08-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='BlogPostTop',
            field=models.BooleanField(default=False, verbose_name='BlogPostTop'),
        ),
    ]
