# Generated by Django 4.0.4 on 2022-08-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='0', max_length=225, verbose_name='token')),
                ('Sessionkey', models.CharField(default='0', max_length=225, verbose_name='Sessionkey')),
            ],
            options={
                'verbose_name_plural': 'MySession',
            },
        ),
    ]
