# Generated by Django 4.0.4 on 2022-08-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='password',
            field=models.CharField(max_length=64, null=True, verbose_name='userpassword'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='sex',
            field=models.CharField(default='man', max_length=10, verbose_name='sex'),
        ),
    ]
