# Generated by Django 4.0.4 on 2022-08-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_mysession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysession',
            name='id',
        ),
        migrations.AlterField(
            model_name='mysession',
            name='token',
            field=models.CharField(max_length=225, primary_key=True, serialize=False, verbose_name='token'),
        ),
    ]
