# Generated by Django 4.0.4 on 2022-08-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userinformation_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='password',
            field=models.TextField(max_length=64, null=True, verbose_name='userpassword'),
        ),
    ]
