# Generated by Django 4.0.4 on 2022-08-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_mysession_id_alter_mysession_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='password',
            field=models.TextField(max_length=225, null=True, verbose_name='userpassword'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='userImg',
            field=models.ImageField(upload_to='usersImg/', verbose_name='img'),
        ),
    ]
