# Generated by Django 4.0.4 on 2022-08-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userinformation_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='userImg',
            field=models.ImageField(upload_to='', verbose_name='img'),
        ),
    ]
