# Generated by Django 4.0.4 on 2022-08-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userinformation_userimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='userImg',
            field=models.ImageField(upload_to='usersImg', verbose_name='img'),
        ),
    ]
