# Generated by Django 4.0.4 on 2022-08-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userinformation_userimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
