# Generated by Django 4.0.4 on 2022-07-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiangyeapp', '0002_userinformation_uesrimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='uesrImg',
            field=models.ImageField(default=0, upload_to='usersImg/', verbose_name='img'),
        ),
    ]
