# Generated by Django 4.0.4 on 2022-07-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiangyeapp', '0003_alter_userinformation_uesrimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
