# Generated by Django 4.0.4 on 2022-07-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiangyeapp', '0004_alter_userinformation_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='date',
            field=models.IntegerField(default=2, null=True),
        ),
    ]
