# Generated by Django 4.0.4 on 2022-07-31 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiangyeapp', '0005_alter_userinformation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='uesrImg',
            new_name='userImg',
        ),
    ]
