# Generated by Django 4.0.4 on 2022-08-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiangyeapp', '0007_alter_userinformation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='name',
        ),
    ]
