# Generated by Django 4.0.4 on 2022-08-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiangyeapp', '0008_remove_userinformation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='username',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='usersname'),
        ),
    ]
