# Generated by Django 4.0.4 on 2022-08-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiangyeapp', '0009_alter_userinformation_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='user_permissions',
        ),
    ]
