# Generated by Django 4.0.4 on 2022-08-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesList', '0002_alter_moviesinformation_user_id'),
        ('jiangyeapp', '0010_delete_department_delete_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userinformation',
        ),
    ]
