# Generated by Django 4.0.4 on 2022-07-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID自增')),
                ('title', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='usersname')),
                ('password', models.CharField(max_length=32, null=True, verbose_name='userpassword')),
                ('age', models.IntegerField(null=True)),
                ('size', models.IntegerField(null=True)),
                ('date', models.IntegerField(default=2)),
                ('create_time', models.DateTimeField(blank=True)),
                ('email', models.CharField(max_length=32, null=True, verbose_name='email')),
            ],
        ),
    ]
